// Do not edit this file!  It was generated by Melati POEM's DSD preprocessor.

package org.melati.doc.example;

import org.melati.poem.*;

public class BuyerTypeBase extends Persistent {

  public final BuyerTypeData dataSnapshot()
      throws AccessPoemException {
    return (BuyerTypeData)_dataSnapshot();
  }

  protected final BuyerTypeData dataForReading()
      throws AccessPoemException {
    return (BuyerTypeData)_dataForReading();
  }

  protected final BuyerTypeData dataForWriting()
      throws AccessPoemException {
    return (BuyerTypeData)_dataForWriting();
  }

  public BuyerTypeTable getBuyerTypeTable() {
    return (BuyerTypeTable)getTable();
  }

  public Integer getId()
      throws AccessPoemException {
    return dataForReading().id;
  }

  public void setId(Integer value)
      throws AccessPoemException, ValidationPoemException {
    getBuyerTypeTable().getIdColumn().getType().assertValidValue(value);
    dataForWriting().id = value;
  }

  public final void setId(int value)
      throws AccessPoemException, ValidationPoemException {
    setId(new Integer(value));
  }

  public final Field getIdField() throws AccessPoemException {
    return getBuyerTypeTable().getIdColumn().asField(this);
  }

  public String getDescription()
      throws AccessPoemException {
    return dataForReading().description;
  }

  public void setDescription(String value)
      throws AccessPoemException, ValidationPoemException {
    getBuyerTypeTable().getDescriptionColumn().getType().assertValidValue(value);
    dataForWriting().description = value;
  }

  public final Field getDescriptionField() throws AccessPoemException {
    return getBuyerTypeTable().getDescriptionColumn().asField(this);
  }
}
