// Do not edit this file!  It was generated by Melati POEM's DSD preprocessor.

package org.melati.doc.example;

import org.melati.poem.*;

public class BuyerTableBase extends Table {

  private Column col_id = null;
  private Column col_name = null;
  private Column col_type = null;

  public BuyerTableBase(Database database, String name) throws PoemException {
    super(database, name, DefinitionSource.dsd);
  }

  protected void init() throws PoemException {
    defineColumn(col_id =
        new Column(this, "id", TroidPoemType.it, DefinitionSource.dsd) { 
          public Object getIdent(Data data) {
            return (Integer)((BuyerData)data).id;
          }

          public void setIdent(Data data, Object ident) {
            ((BuyerData)data).id = (Integer)ident;
          }

          public Object getValue(Persistent g)
              throws AccessPoemException, PoemException {
            return ((Buyer)g).getId();
          }

          public void setValue(Persistent g, Object value)
              throws AccessPoemException, ValidationPoemException {
            ((Buyer)g).setId((Integer)value);
          }

          protected boolean defaultUserEditable() {
            return false;
          }

          protected int defaultDisplayOrder() {
            return 0;
          }

          public Object getIdent(Persistent g)
              throws AccessPoemException {
            return ((Buyer)g).getId();
          }

          public void setIdent(Persistent g, Object ident)
              throws AccessPoemException {
            ((Buyer)g).setId((Integer)ident);
          }
        });

    defineColumn(col_name =
        new Column(this, "name", new StringPoemType(false, 25), DefinitionSource.dsd) { 
          public Object getIdent(Data data) {
            return (String)((BuyerData)data).name;
          }

          public void setIdent(Data data, Object ident) {
            ((BuyerData)data).name = (String)ident;
          }

          public Object getValue(Persistent g)
              throws AccessPoemException, PoemException {
            return ((Buyer)g).getName();
          }

          public void setValue(Persistent g, Object value)
              throws AccessPoemException, ValidationPoemException {
            ((Buyer)g).setName((String)value);
          }

          protected boolean defaultPrimaryDisplay() {
            return true;
          }

          protected Integer defaultDisplayOrderPriority() {
            return new Integer(0);
          }

          protected int defaultDisplayOrder() {
            return 1;
          }

          protected String defaultDescription() {
            return "The buyer's name";
          }

          protected boolean defaultUnique() {
            return true;
          }

          public Object getIdent(Persistent g)
              throws AccessPoemException {
            return ((Buyer)g).getName();
          }

          public void setIdent(Persistent g, Object ident)
              throws AccessPoemException {
            ((Buyer)g).setName((String)ident);
          }
        });

    defineColumn(col_type =
        new Column(this, "type", new ReferencePoemType(((ExampleDatabase)getDatabase()).getBuyerTypeTable(), false), DefinitionSource.dsd) { 
          public Object getIdent(Data data) {
            return (Integer)((BuyerData)data).type;
          }

          public void setIdent(Data data, Object ident) {
            ((BuyerData)data).type = (Integer)ident;
          }

          public Object getValue(Persistent g)
              throws AccessPoemException, PoemException {
            return ((Buyer)g).getType();
          }

          public void setValue(Persistent g, Object value)
              throws AccessPoemException, ValidationPoemException {
            ((Buyer)g).setType((BuyerType)value);
          }

          protected int defaultDisplayOrder() {
            return 2;
          }

          protected String defaultDescription() {
            return "The buyer's type";
          }

          protected boolean defaultIndexed() {
            return true;
          }

          public Object getIdent(Persistent g)
              throws AccessPoemException {
            return ((Buyer)g).getTypeTroid();
          }

          public void setIdent(Persistent g, Object ident)
              throws AccessPoemException {
            ((Buyer)g).setTypeTroid((Integer)ident);
          }
        });
  }

  public final Column getIdColumn() {
    return col_id;
  }

  public final Column getNameColumn() {
    return col_name;
  }

  public final Column getTypeColumn() {
    return col_type;
  }

  public Buyer getBuyerObject(Integer troid) {
    return (Buyer)getObject(troid);
  }

  public Buyer getBuyerObject(int troid) {
    return (Buyer)getObject(troid);
  }

  protected Persistent newPersistent() {
    return new Buyer();
  }

  protected Data _newData() {
    return new BuyerData();
  }
  protected String defaultDescription() {
    return "Someone buying something";
  }

  protected int defaultDisplayOrder() {
    return 0;
  }
}
