// Do not edit this file!  It was generated by Melati POEM's DSD preprocessor.

package org.melati.doc.example;

import org.melati.poem.*;

public class BuyerDataBase extends Data {
  Integer id;
  String name;
  Integer type;
}
