// Do not edit this file!  It was generated by Melati POEM's DSD preprocessor.

package org.melati.doc.example;

import org.melati.poem.*;

public class BuyerTypeBase extends Persistent {

  public BuyerTypeTable getBuyerTypeTable() {
    return (BuyerTypeTable)getTable();
  }

  Integer id;
  String description;

  public Integer getId_unsafe() {
    return id;
  }

  public void setId_unsafe(Integer value) {
    id = value;
  }

  public Integer getId()
      throws AccessPoemException {
    readLock();
    return getId_unsafe();
  }

  public void setId(Integer value)
      throws AccessPoemException, ValidationPoemException {
    getBuyerTypeTable().getIdColumn().getType().assertValidValue(value);
    writeLock();
    setId_unsafe(value);
  }

  public final void setId(int value)
      throws AccessPoemException, ValidationPoemException {
    setId(new Integer(value));
  }

  public final Field getIdField() throws AccessPoemException {
    return getBuyerTypeTable().getIdColumn().asField(this);
  }

  public String getDescription_unsafe() {
    return description;
  }

  public void setDescription_unsafe(String value) {
    description = value;
  }

  public String getDescription()
      throws AccessPoemException {
    readLock();
    return getDescription_unsafe();
  }

  public void setDescription(String value)
      throws AccessPoemException, ValidationPoemException {
    getBuyerTypeTable().getDescriptionColumn().getType().assertValidValue(value);
    writeLock();
    setDescription_unsafe(value);
  }

  public final Field getDescriptionField() throws AccessPoemException {
    return getBuyerTypeTable().getDescriptionColumn().asField(this);
  }
}
