// Do not edit this file!  It was generated by Melati POEM's DSD preprocessor.

package org.melati.doc.example;

import org.melati.poem.*;

public class BuyerBase extends Persistent {

  public final BuyerData dataSnapshot()
      throws AccessPoemException {
    return (BuyerData)_dataSnapshot();
  }

  protected final BuyerData dataForReading()
      throws AccessPoemException {
    return (BuyerData)_dataForReading();
  }

  protected final BuyerData dataForWriting()
      throws AccessPoemException {
    return (BuyerData)_dataForWriting();
  }

  public BuyerTable getBuyerTable() {
    return (BuyerTable)getTable();
  }

  public Integer getId()
      throws AccessPoemException {
    return dataForReading().id;
  }

  public void setId(Integer value)
      throws AccessPoemException, ValidationPoemException {
    getBuyerTable().getIdColumn().getType().assertValidValue(value);
    dataForWriting().id = value;
  }

  public final void setId(int value)
      throws AccessPoemException, ValidationPoemException {
    setId(new Integer(value));
  }

  public final Field getIdField() throws AccessPoemException {
    return getBuyerTable().getIdColumn().asField(this);
  }

  public String getName()
      throws AccessPoemException {
    return dataForReading().name;
  }

  public void setName(String value)
      throws AccessPoemException, ValidationPoemException {
    getBuyerTable().getNameColumn().getType().assertValidValue(value);
    dataForWriting().name = value;
  }

  public final Field getNameField() throws AccessPoemException {
    return getBuyerTable().getNameColumn().asField(this);
  }

  public Integer getTypeTroid()
      throws AccessPoemException {
    return dataForReading().type;
  }

  public void setTypeTroid(Integer ident)
      throws AccessPoemException {
    dataForWriting().type = ident;
  }

  public BuyerType getType()
      throws AccessPoemException, NoSuchRowPoemException {
    Integer troid = getTypeTroid();
    return troid == null ? null :
        ((ExampleDatabase)getDatabase()).getBuyerTypeTable().getBuyerTypeObject(troid);
  }

  public void setType(BuyerType value)
      throws AccessPoemException {
    setTypeTroid(value == null ? null : value.troid());
  }

  public final Field getTypeField() throws AccessPoemException {
    return getBuyerTable().getTypeColumn().asField(this);
  }
}
