// Do not edit this file!  It was generated by Melati POEM's DSD preprocessor.

package org.melati.doc.example;

import java.util.*;
import java.sql.Date;
import org.melati.util.*;
import org.melati.poem.*;

public class BuyerBase extends Persistent {

  public BuyerTable getBuyerTable() {
    return (BuyerTable)getTable();
  }

  private BuyerTable _getBuyerTable() {
    return (BuyerTable)getTable();
  }

  Integer id;
  String name;
  Integer type;

  public Integer getId_unsafe() {
    return id;
  }

  public void setId_unsafe(Integer cooked) {
    id = cooked;
  }

  public Integer getId()
      throws AccessPoemException {
    readLock();
    return getId_unsafe();
  }

  public void setId(Integer cooked)
      throws AccessPoemException, ValidationPoemException {
    _getBuyerTable().getIdColumn().getType().assertValidCooked(cooked);
    writeLock();
    setId_unsafe(cooked);
  }

  public final void setId(int cooked)
      throws AccessPoemException, ValidationPoemException {
    setId(new Integer(cooked));
  }

  public final Field getIdField() throws AccessPoemException {
    return _getBuyerTable().getIdColumn().asField(this);
  }

  public String getName_unsafe() {
    return name;
  }

  public void setName_unsafe(String cooked) {
    name = cooked;
  }

  public String getName()
      throws AccessPoemException {
    readLock();
    return getName_unsafe();
  }

  public void setName(String cooked)
      throws AccessPoemException, ValidationPoemException {
    _getBuyerTable().getNameColumn().getType().assertValidCooked(cooked);
    writeLock();
    setName_unsafe(cooked);
  }

  public final Field getNameField() throws AccessPoemException {
    return _getBuyerTable().getNameColumn().asField(this);
  }

  public Integer getType_unsafe() {
    return type;
  }

  public void setType_unsafe(Integer cooked) {
    type = cooked;
  }

  public Integer getTypeTroid()
      throws AccessPoemException {
    readLock();
    return getType_unsafe();
  }

  public void setTypeTroid(Integer raw)
      throws AccessPoemException {
    getBuyerTable().getTypeColumn().getType().assertValidRaw(raw);
    writeLock();
    setType_unsafe(raw);
  }

  public BuyerType getType()
      throws AccessPoemException, NoSuchRowPoemException {
    Integer troid = getTypeTroid();
    return troid == null ? null :
        ((ExampleDatabase)getDatabase()).getBuyerTypeTable().getBuyerTypeObject(troid);
  }

  public void setType(BuyerType cooked)
      throws AccessPoemException {
    setTypeTroid(cooked == null ? null : cooked.troid());
  }

  public final Field getTypeField() throws AccessPoemException {
    return _getBuyerTable().getTypeColumn().asField(this);
  }
}
