// Do not edit this file!  It was generated by Melati POEM's DSD preprocessor.

package org.melati.doc.example;

import org.melati.poem.*;

public class ExampleDatabaseBase extends PoemDatabase {

  private BuyerTable tab_buyer = null;
  private BuyerTypeTable tab_buyertype = null;
  private ProductTable tab_product = null;
  private OrderTable tab_order = null;

  public ExampleDatabaseBase() {
    try {
      defineTable(tab_buyer = new BuyerTable(this, "buyer"));
      defineTable(tab_buyertype = new BuyerTypeTable(this, "buyertype"));
      defineTable(tab_product = new ProductTable(this, "product"));
      defineTable(tab_order = new OrderTable(this, "order"));
      tab_buyer.init();
      tab_buyertype.init();
      tab_product.init();
      tab_order.init();
    }
    catch (PoemException e) {
      throw new UnexpectedExceptionPoemException(e);
    }
  }

  public BuyerTable getBuyerTable() {
    return tab_buyer;
  }

  public BuyerTypeTable getBuyerTypeTable() {
    return tab_buyertype;
  }

  public ProductTable getProductTable() {
    return tab_product;
  }

  public OrderTable getOrderTable() {
    return tab_order;
  }
}
