// Do not edit this file!  It was generated by Melati POEM's DSD preprocessor.

package org.melati.doc.example;

import java.util.*;
import java.sql.Date;
import org.melati.util.*;
import org.melati.poem.*;

public class ExampleDatabaseBase extends PoemDatabase {

  private BuyerTable tab_buyer = null;
  private BuyerTypeTable tab_buyertype = null;
  private ProductTable tab_product = null;
  private OrderTable tab_order = null;

  protected ExampleDatabaseBase() {
    redefineTable(tab_buyer = new BuyerTable(this, "buyer", DefinitionSource.dsd));
    redefineTable(tab_buyertype = new BuyerTypeTable(this, "buyertype", DefinitionSource.dsd));
    redefineTable(tab_product = new ProductTable(this, "product", DefinitionSource.dsd));
    redefineTable(tab_order = new OrderTable(this, "order", DefinitionSource.dsd));
  }

  public BuyerTable getBuyerTable() {
    return tab_buyer;
  }

  public BuyerTypeTable getBuyerTypeTable() {
    return tab_buyertype;
  }

  public ProductTable getProductTable() {
    return tab_product;
  }

  public OrderTable getOrderTable() {
    return tab_order;
  }
}
