// Do not edit this file!  It was generated by Melati POEM's DSD preprocessor.

package org.melati.doc.example;

import org.melati.poem.*;

public class OrderDataBase extends Data {
  Integer id;
  Integer buyer;
  Integer product;
  Boolean urgent;
}
