// Do not edit this file!  It was generated by Melati Poem's DSD preprocessor.

package org.melati.poem;

public class ColumnInfoDataBase extends Data {
  Integer id;
  Integer tableinfo;
  String name;
  String displayname;
  String description;
  Integer displayorder;
  Boolean usereditable;
  Boolean displayable;
  Boolean primarydisplay;
  Integer displayorderpriority;
  Integer typecode;
  Boolean nullable;
  Integer size;
  Integer width;
  Integer height;
  Integer targettable;
  String renderinfo;
}
