// Do not edit this file!  It was generated by Melati POEM's DSD preprocessor.

package org.melati.poem;

public class ColumnInfoDataBase extends Data {
  Integer id;
  Integer tableinfo;
  String name;
  String displayname;
  String description;
  Integer displayorder;
  Boolean usereditable;
  Boolean recorddisplay;
  Boolean summarydisplay;
  Boolean primarydisplay;
  Boolean searchcriterion;
  Integer displayorderpriority;
  Integer type;
  Boolean nullable;
  Boolean indexed;
  Boolean unique;
  Integer size;
  Integer width;
  Integer height;
  String renderinfo;
}
