// Do not edit this file!  It was generated by Melati POEM's DSD preprocessor.

package org.melati.poem;

public class ColumnInfoBase extends Persistent {

  public ColumnInfoTable getColumnInfoTable() {
    return (ColumnInfoTable)getTable();
  }

  Integer id;
  Integer tableinfo;
  String name;
  String displayname;
  String description;
  Integer displayorder;
  Boolean usereditable;
  Boolean recorddisplay;
  Boolean summarydisplay;
  Boolean primarydisplay;
  Boolean searchcriterion;
  Integer displayorderpriority;
  Integer type;
  Boolean nullable;
  Boolean indexed;
  Boolean unique;
  Integer size;
  Integer width;
  Integer height;
  String renderinfo;

  public Integer getId_unsafe() {
    return id;
  }

  public void setId_unsafe(Integer cooked) {
    id = cooked;
  }

  public Integer getId()
      throws AccessPoemException {
    readLock();
    return getId_unsafe();
  }

  public void setId(Integer cooked)
      throws AccessPoemException, ValidationPoemException {
    getColumnInfoTable().getIdColumn().getType().assertValidCooked(cooked);
    writeLock();
    setId_unsafe(cooked);
  }

  public final void setId(int cooked)
      throws AccessPoemException, ValidationPoemException {
    setId(new Integer(cooked));
  }

  public final Field getIdField() throws AccessPoemException {
    return getColumnInfoTable().getIdColumn().asField(this);
  }

  public Integer getTableinfo_unsafe() {
    return tableinfo;
  }

  public void setTableinfo_unsafe(Integer cooked) {
    tableinfo = cooked;
  }

  public Integer getTableinfoTroid()
      throws AccessPoemException {
    readLock();
    return getTableinfo_unsafe();
  }

  public void setTableinfoTroid(Integer raw)
      throws AccessPoemException {
    getColumnInfoTable().getTableinfoColumn().getType().assertValidRaw(raw);
    writeLock();
    setTableinfo_unsafe(raw);
  }

  public TableInfo getTableinfo()
      throws AccessPoemException, NoSuchRowPoemException {
    Integer troid = getTableinfoTroid();
    return troid == null ? null :
        ((PoemDatabase)getDatabase()).getTableInfoTable().getTableInfoObject(troid);
  }

  public void setTableinfo(TableInfo cooked)
      throws AccessPoemException {
    setTableinfoTroid(cooked == null ? null : cooked.troid());
  }

  public final Field getTableinfoField() throws AccessPoemException {
    return getColumnInfoTable().getTableinfoColumn().asField(this);
  }

  public String getName_unsafe() {
    return name;
  }

  public void setName_unsafe(String cooked) {
    name = cooked;
  }

  public String getName()
      throws AccessPoemException {
    readLock();
    return getName_unsafe();
  }

  public void setName(String cooked)
      throws AccessPoemException, ValidationPoemException {
    getColumnInfoTable().getNameColumn().getType().assertValidCooked(cooked);
    writeLock();
    setName_unsafe(cooked);
  }

  public final Field getNameField() throws AccessPoemException {
    return getColumnInfoTable().getNameColumn().asField(this);
  }

  public String getDisplayname_unsafe() {
    return displayname;
  }

  public void setDisplayname_unsafe(String cooked) {
    displayname = cooked;
  }

  public String getDisplayname()
      throws AccessPoemException {
    readLock();
    return getDisplayname_unsafe();
  }

  public void setDisplayname(String cooked)
      throws AccessPoemException, ValidationPoemException {
    getColumnInfoTable().getDisplaynameColumn().getType().assertValidCooked(cooked);
    writeLock();
    setDisplayname_unsafe(cooked);
  }

  public final Field getDisplaynameField() throws AccessPoemException {
    return getColumnInfoTable().getDisplaynameColumn().asField(this);
  }

  public String getDescription_unsafe() {
    return description;
  }

  public void setDescription_unsafe(String cooked) {
    description = cooked;
  }

  public String getDescription()
      throws AccessPoemException {
    readLock();
    return getDescription_unsafe();
  }

  public void setDescription(String cooked)
      throws AccessPoemException, ValidationPoemException {
    getColumnInfoTable().getDescriptionColumn().getType().assertValidCooked(cooked);
    writeLock();
    setDescription_unsafe(cooked);
  }

  public final Field getDescriptionField() throws AccessPoemException {
    return getColumnInfoTable().getDescriptionColumn().asField(this);
  }

  public Integer getDisplayorder_unsafe() {
    return displayorder;
  }

  public void setDisplayorder_unsafe(Integer cooked) {
    displayorder = cooked;
  }

  public Integer getDisplayorder()
      throws AccessPoemException {
    readLock();
    return getDisplayorder_unsafe();
  }

  public void setDisplayorder(Integer cooked)
      throws AccessPoemException, ValidationPoemException {
    getColumnInfoTable().getDisplayorderColumn().getType().assertValidCooked(cooked);
    writeLock();
    setDisplayorder_unsafe(cooked);
  }

  public final void setDisplayorder(int cooked)
      throws AccessPoemException, ValidationPoemException {
    setDisplayorder(new Integer(cooked));
  }

  public final Field getDisplayorderField() throws AccessPoemException {
    return getColumnInfoTable().getDisplayorderColumn().asField(this);
  }

  public Boolean getUsereditable_unsafe() {
    return usereditable;
  }

  public void setUsereditable_unsafe(Boolean cooked) {
    usereditable = cooked;
  }

  public Boolean getUsereditable()
      throws AccessPoemException {
    readLock();
    return getUsereditable_unsafe();
  }

  public void setUsereditable(Boolean cooked)
      throws AccessPoemException, ValidationPoemException {
    getColumnInfoTable().getUsereditableColumn().getType().assertValidCooked(cooked);
    writeLock();
    setUsereditable_unsafe(cooked);
  }

  public final void setUsereditable(boolean cooked)
      throws AccessPoemException, ValidationPoemException {
    setUsereditable(cooked ? Boolean.TRUE : Boolean.FALSE);
  }

  public final Field getUsereditableField() throws AccessPoemException {
    return getColumnInfoTable().getUsereditableColumn().asField(this);
  }

  public Boolean getRecorddisplay_unsafe() {
    return recorddisplay;
  }

  public void setRecorddisplay_unsafe(Boolean cooked) {
    recorddisplay = cooked;
  }

  public Boolean getRecorddisplay()
      throws AccessPoemException {
    readLock();
    return getRecorddisplay_unsafe();
  }

  public void setRecorddisplay(Boolean cooked)
      throws AccessPoemException, ValidationPoemException {
    getColumnInfoTable().getRecorddisplayColumn().getType().assertValidCooked(cooked);
    writeLock();
    setRecorddisplay_unsafe(cooked);
  }

  public final void setRecorddisplay(boolean cooked)
      throws AccessPoemException, ValidationPoemException {
    setRecorddisplay(cooked ? Boolean.TRUE : Boolean.FALSE);
  }

  public final Field getRecorddisplayField() throws AccessPoemException {
    return getColumnInfoTable().getRecorddisplayColumn().asField(this);
  }

  public Boolean getSummarydisplay_unsafe() {
    return summarydisplay;
  }

  public void setSummarydisplay_unsafe(Boolean cooked) {
    summarydisplay = cooked;
  }

  public Boolean getSummarydisplay()
      throws AccessPoemException {
    readLock();
    return getSummarydisplay_unsafe();
  }

  public void setSummarydisplay(Boolean cooked)
      throws AccessPoemException, ValidationPoemException {
    getColumnInfoTable().getSummarydisplayColumn().getType().assertValidCooked(cooked);
    writeLock();
    setSummarydisplay_unsafe(cooked);
  }

  public final void setSummarydisplay(boolean cooked)
      throws AccessPoemException, ValidationPoemException {
    setSummarydisplay(cooked ? Boolean.TRUE : Boolean.FALSE);
  }

  public final Field getSummarydisplayField() throws AccessPoemException {
    return getColumnInfoTable().getSummarydisplayColumn().asField(this);
  }

  public Boolean getPrimarydisplay_unsafe() {
    return primarydisplay;
  }

  public void setPrimarydisplay_unsafe(Boolean cooked) {
    primarydisplay = cooked;
  }

  public Boolean getPrimarydisplay()
      throws AccessPoemException {
    readLock();
    return getPrimarydisplay_unsafe();
  }

  public void setPrimarydisplay(Boolean cooked)
      throws AccessPoemException, ValidationPoemException {
    getColumnInfoTable().getPrimarydisplayColumn().getType().assertValidCooked(cooked);
    writeLock();
    setPrimarydisplay_unsafe(cooked);
  }

  public final void setPrimarydisplay(boolean cooked)
      throws AccessPoemException, ValidationPoemException {
    setPrimarydisplay(cooked ? Boolean.TRUE : Boolean.FALSE);
  }

  public final Field getPrimarydisplayField() throws AccessPoemException {
    return getColumnInfoTable().getPrimarydisplayColumn().asField(this);
  }

  public Boolean getSearchcriterion_unsafe() {
    return searchcriterion;
  }

  public void setSearchcriterion_unsafe(Boolean cooked) {
    searchcriterion = cooked;
  }

  public Boolean getSearchcriterion()
      throws AccessPoemException {
    readLock();
    return getSearchcriterion_unsafe();
  }

  public void setSearchcriterion(Boolean cooked)
      throws AccessPoemException, ValidationPoemException {
    getColumnInfoTable().getSearchcriterionColumn().getType().assertValidCooked(cooked);
    writeLock();
    setSearchcriterion_unsafe(cooked);
  }

  public final void setSearchcriterion(boolean cooked)
      throws AccessPoemException, ValidationPoemException {
    setSearchcriterion(cooked ? Boolean.TRUE : Boolean.FALSE);
  }

  public final Field getSearchcriterionField() throws AccessPoemException {
    return getColumnInfoTable().getSearchcriterionColumn().asField(this);
  }

  public Integer getDisplayorderpriority_unsafe() {
    return displayorderpriority;
  }

  public void setDisplayorderpriority_unsafe(Integer cooked) {
    displayorderpriority = cooked;
  }

  public Integer getDisplayorderpriority()
      throws AccessPoemException {
    readLock();
    return getDisplayorderpriority_unsafe();
  }

  public void setDisplayorderpriority(Integer cooked)
      throws AccessPoemException, ValidationPoemException {
    getColumnInfoTable().getDisplayorderpriorityColumn().getType().assertValidCooked(cooked);
    writeLock();
    setDisplayorderpriority_unsafe(cooked);
  }

  public final void setDisplayorderpriority(int cooked)
      throws AccessPoemException, ValidationPoemException {
    setDisplayorderpriority(new Integer(cooked));
  }

  public final Field getDisplayorderpriorityField() throws AccessPoemException {
    return getColumnInfoTable().getDisplayorderpriorityColumn().asField(this);
  }

  public Integer getType_unsafe() {
    return type;
  }

  public void setType_unsafe(Integer cooked) {
    type = cooked;
  }

  public Integer getTypeCode()
      throws AccessPoemException {
    readLock();
    return getType_unsafe();
  }

  public void setTypeCode(Integer raw)
      throws AccessPoemException {
    getColumnInfoTable().getTypeColumn().getType().assertValidRaw(raw);
    writeLock();
    setType_unsafe(raw);
  }

  public PoemTypeFactory getType()
      throws AccessPoemException {
    Integer code = getTypeCode();
    return code == null ? null :
        PoemTypeFactory.forCode(getDatabase(), code.intValue());
  }

  public void setType(PoemTypeFactory cooked)
      throws AccessPoemException {
    setTypeCode(cooked == null ? null : cooked.code);
  }

  public final Field getTypeField() throws AccessPoemException {
    return getColumnInfoTable().getTypeColumn().asField(this);
  }

  public Boolean getNullable_unsafe() {
    return nullable;
  }

  public void setNullable_unsafe(Boolean cooked) {
    nullable = cooked;
  }

  public Boolean getNullable()
      throws AccessPoemException {
    readLock();
    return getNullable_unsafe();
  }

  public void setNullable(Boolean cooked)
      throws AccessPoemException, ValidationPoemException {
    getColumnInfoTable().getNullableColumn().getType().assertValidCooked(cooked);
    writeLock();
    setNullable_unsafe(cooked);
  }

  public final void setNullable(boolean cooked)
      throws AccessPoemException, ValidationPoemException {
    setNullable(cooked ? Boolean.TRUE : Boolean.FALSE);
  }

  public final Field getNullableField() throws AccessPoemException {
    return getColumnInfoTable().getNullableColumn().asField(this);
  }

  public Boolean getIndexed_unsafe() {
    return indexed;
  }

  public void setIndexed_unsafe(Boolean cooked) {
    indexed = cooked;
  }

  public Boolean getIndexed()
      throws AccessPoemException {
    readLock();
    return getIndexed_unsafe();
  }

  public void setIndexed(Boolean cooked)
      throws AccessPoemException, ValidationPoemException {
    getColumnInfoTable().getIndexedColumn().getType().assertValidCooked(cooked);
    writeLock();
    setIndexed_unsafe(cooked);
  }

  public final void setIndexed(boolean cooked)
      throws AccessPoemException, ValidationPoemException {
    setIndexed(cooked ? Boolean.TRUE : Boolean.FALSE);
  }

  public final Field getIndexedField() throws AccessPoemException {
    return getColumnInfoTable().getIndexedColumn().asField(this);
  }

  public Boolean getUnique_unsafe() {
    return unique;
  }

  public void setUnique_unsafe(Boolean cooked) {
    unique = cooked;
  }

  public Boolean getUnique()
      throws AccessPoemException {
    readLock();
    return getUnique_unsafe();
  }

  public void setUnique(Boolean cooked)
      throws AccessPoemException, ValidationPoemException {
    getColumnInfoTable().getUniqueColumn().getType().assertValidCooked(cooked);
    writeLock();
    setUnique_unsafe(cooked);
  }

  public final void setUnique(boolean cooked)
      throws AccessPoemException, ValidationPoemException {
    setUnique(cooked ? Boolean.TRUE : Boolean.FALSE);
  }

  public final Field getUniqueField() throws AccessPoemException {
    return getColumnInfoTable().getUniqueColumn().asField(this);
  }

  public Integer getSize_unsafe() {
    return size;
  }

  public void setSize_unsafe(Integer cooked) {
    size = cooked;
  }

  public Integer getSize()
      throws AccessPoemException {
    readLock();
    return getSize_unsafe();
  }

  public void setSize(Integer cooked)
      throws AccessPoemException, ValidationPoemException {
    getColumnInfoTable().getSizeColumn().getType().assertValidCooked(cooked);
    writeLock();
    setSize_unsafe(cooked);
  }

  public final void setSize(int cooked)
      throws AccessPoemException, ValidationPoemException {
    setSize(new Integer(cooked));
  }

  public final Field getSizeField() throws AccessPoemException {
    return getColumnInfoTable().getSizeColumn().asField(this);
  }

  public Integer getWidth_unsafe() {
    return width;
  }

  public void setWidth_unsafe(Integer cooked) {
    width = cooked;
  }

  public Integer getWidth()
      throws AccessPoemException {
    readLock();
    return getWidth_unsafe();
  }

  public void setWidth(Integer cooked)
      throws AccessPoemException, ValidationPoemException {
    getColumnInfoTable().getWidthColumn().getType().assertValidCooked(cooked);
    writeLock();
    setWidth_unsafe(cooked);
  }

  public final void setWidth(int cooked)
      throws AccessPoemException, ValidationPoemException {
    setWidth(new Integer(cooked));
  }

  public final Field getWidthField() throws AccessPoemException {
    return getColumnInfoTable().getWidthColumn().asField(this);
  }

  public Integer getHeight_unsafe() {
    return height;
  }

  public void setHeight_unsafe(Integer cooked) {
    height = cooked;
  }

  public Integer getHeight()
      throws AccessPoemException {
    readLock();
    return getHeight_unsafe();
  }

  public void setHeight(Integer cooked)
      throws AccessPoemException, ValidationPoemException {
    getColumnInfoTable().getHeightColumn().getType().assertValidCooked(cooked);
    writeLock();
    setHeight_unsafe(cooked);
  }

  public final void setHeight(int cooked)
      throws AccessPoemException, ValidationPoemException {
    setHeight(new Integer(cooked));
  }

  public final Field getHeightField() throws AccessPoemException {
    return getColumnInfoTable().getHeightColumn().asField(this);
  }

  public String getRenderinfo_unsafe() {
    return renderinfo;
  }

  public void setRenderinfo_unsafe(String cooked) {
    renderinfo = cooked;
  }

  public String getRenderinfo()
      throws AccessPoemException {
    readLock();
    return getRenderinfo_unsafe();
  }

  public void setRenderinfo(String cooked)
      throws AccessPoemException, ValidationPoemException {
    getColumnInfoTable().getRenderinfoColumn().getType().assertValidCooked(cooked);
    writeLock();
    setRenderinfo_unsafe(cooked);
  }

  public final Field getRenderinfoField() throws AccessPoemException {
    return getColumnInfoTable().getRenderinfoColumn().asField(this);
  }
}
