// Do not edit this file!  It was generated by Melati Poem's DSD preprocessor.

package org.melati.poem;

class GroupCapabilityDataBase extends Data {
  Integer id;
  Integer group;
  Integer capability;
}
