// Do not edit this file!  It was generated by Melati Poem's DSD preprocessor.

package org.melati.poem;

public class GroupMembershipBase extends Persistent {

  public final GroupMembershipData dataSnapshot()
      throws AccessPoemException {
    return (GroupMembershipData)_dataSnapshot();
  }

  protected final GroupMembershipData dataForReading()
      throws AccessPoemException {
    return (GroupMembershipData)_dataForReading();
  }

  protected final GroupMembershipData dataForWriting()
      throws AccessPoemException {
    return (GroupMembershipData)_dataForWriting();
  }

  public GroupMembershipTable getGroupMembershipTable() {
    return (GroupMembershipTable)getTable();
  }

  public Integer getId()
      throws AccessPoemException {
    return dataForReading().id;
  }

  public void setId(Integer value)
      throws AccessPoemException, ValidationPoemException {
    getGroupMembershipTable().getIdColumn().getType().assertValidValue(value);
    dataForWriting().id = value;
  }

  public final void setId(int value)
      throws AccessPoemException, ValidationPoemException {
    setId(new Integer(value));
  }

  public final Field getIdField() throws AccessPoemException {
    return getGroupMembershipTable().getIdColumn().asField(this);
  }

  public Integer getUserTroid()
      throws AccessPoemException {
    return dataForReading().user;
  }

  public void setUserTroid(Integer ident)
      throws AccessPoemException {
    dataForWriting().user = ident;
  }

  public User getUser()
      throws AccessPoemException, NoSuchRowPoemException {
    Integer troid = getUserTroid();
    return troid == null ? null :
        getDatabase().getUserTable().getUserObject(troid);
  }

  public void setUser(User value)
      throws AccessPoemException {
    setUserTroid(value == null ? null : value.troid());
  }

  public final Field getUserField() throws AccessPoemException {
    return getGroupMembershipTable().getUserColumn().asField(this);
  }

  public Integer getGroupTroid()
      throws AccessPoemException {
    return dataForReading().group;
  }

  public void setGroupTroid(Integer ident)
      throws AccessPoemException {
    dataForWriting().group = ident;
  }

  public Group getGroup()
      throws AccessPoemException, NoSuchRowPoemException {
    Integer troid = getGroupTroid();
    return troid == null ? null :
        getDatabase().getGroupTable().getGroupObject(troid);
  }

  public void setGroup(Group value)
      throws AccessPoemException {
    setGroupTroid(value == null ? null : value.troid());
  }

  public final Field getGroupField() throws AccessPoemException {
    return getGroupMembershipTable().getGroupColumn().asField(this);
  }
}
