// Do not edit this file!  It was generated by Melati Poem's DSD preprocessor.

package org.melati.poem;

class GroupMembershipDataBase extends Data {
  Integer id;
  Integer user;
  Integer group;
}
