// Do not edit this file!  It was generated by Melati POEM's DSD preprocessor.

package org.melati.poem;

public class GroupBase extends Persistent {

  public GroupTable getGroupTable() {
    return (GroupTable)getTable();
  }

  Integer id;
  String name;

  public Integer getId_unsafe() {
    return id;
  }

  public void setId_unsafe(Integer value) {
    id = value;
  }

  public Integer getId()
      throws AccessPoemException {
    readLock();
    return getId_unsafe();
  }

  public void setId(Integer value)
      throws AccessPoemException, ValidationPoemException {
    getGroupTable().getIdColumn().getType().assertValidValue(value);
    writeLock();
    setId_unsafe(value);
  }

  public final void setId(int value)
      throws AccessPoemException, ValidationPoemException {
    setId(new Integer(value));
  }

  public final Field getIdField() throws AccessPoemException {
    return getGroupTable().getIdColumn().asField(this);
  }

  public String getName_unsafe() {
    return name;
  }

  public void setName_unsafe(String value) {
    name = value;
  }

  public String getName()
      throws AccessPoemException {
    readLock();
    return getName_unsafe();
  }

  public void setName(String value)
      throws AccessPoemException, ValidationPoemException {
    getGroupTable().getNameColumn().getType().assertValidValue(value);
    writeLock();
    setName_unsafe(value);
  }

  public final Field getNameField() throws AccessPoemException {
    return getGroupTable().getNameColumn().asField(this);
  }
}
