// Do not edit this file!  It was generated by Melati POEM's DSD preprocessor.

package org.melati.poem;

public class GroupMembershipBase extends Persistent {

  public GroupMembershipTable getGroupMembershipTable() {
    return (GroupMembershipTable)getTable();
  }

  Integer id;
  Integer user;
  Integer group;

  public Integer getId_unsafe() {
    return id;
  }

  public void setId_unsafe(Integer value) {
    id = value;
  }

  public Integer getId()
      throws AccessPoemException {
    readLock();
    return getId_unsafe();
  }

  public void setId(Integer value)
      throws AccessPoemException, ValidationPoemException {
    getGroupMembershipTable().getIdColumn().getType().assertValidValue(value);
    writeLock();
    setId_unsafe(value);
  }

  public final void setId(int value)
      throws AccessPoemException, ValidationPoemException {
    setId(new Integer(value));
  }

  public final Field getIdField() throws AccessPoemException {
    return getGroupMembershipTable().getIdColumn().asField(this);
  }

  public Integer getUser_unsafe() {
    return user;
  }

  public void setUser_unsafe(Integer value) {
    user = value;
  }

  public Integer getUserTroid()
      throws AccessPoemException {
    readLock();
    return getUser_unsafe();
  }

  public void setUserTroid(Integer ident)
      throws AccessPoemException {
    getGroupMembershipTable().getUserColumn().getType().assertValidIdent(ident);
    writeLock();
    setUser_unsafe(ident);
  }

  public User getUser()
      throws AccessPoemException, NoSuchRowPoemException {
    Integer troid = getUserTroid();
    return troid == null ? null :
        ((PoemDatabase)getDatabase()).getUserTable().getUserObject(troid);
  }

  public void setUser(User value)
      throws AccessPoemException {
    setUserTroid(value == null ? null : value.troid());
  }

  public final Field getUserField() throws AccessPoemException {
    return getGroupMembershipTable().getUserColumn().asField(this);
  }

  public Integer getGroup_unsafe() {
    return group;
  }

  public void setGroup_unsafe(Integer value) {
    group = value;
  }

  public Integer getGroupTroid()
      throws AccessPoemException {
    readLock();
    return getGroup_unsafe();
  }

  public void setGroupTroid(Integer ident)
      throws AccessPoemException {
    getGroupMembershipTable().getGroupColumn().getType().assertValidIdent(ident);
    writeLock();
    setGroup_unsafe(ident);
  }

  public Group getGroup()
      throws AccessPoemException, NoSuchRowPoemException {
    Integer troid = getGroupTroid();
    return troid == null ? null :
        ((PoemDatabase)getDatabase()).getGroupTable().getGroupObject(troid);
  }

  public void setGroup(Group value)
      throws AccessPoemException {
    setGroupTroid(value == null ? null : value.troid());
  }

  public final Field getGroupField() throws AccessPoemException {
    return getGroupMembershipTable().getGroupColumn().asField(this);
  }
}
