// Do not edit this file!  It was generated by Melati POEM's DSD preprocessor.

package org.melati.poem;

public class GroupCapabilityDataBase extends Data {
  Integer id;
  Integer group;
  Integer capability;
}
