// Do not edit this file!  It was generated by Melati Poem's DSD preprocessor.

package org.melati.poem;

class PoemDatabaseBase extends Database {

  private TableInfoTable tab_tableinfo = null;
  private ColumnInfoTable tab_columninfo = null;
  private CapabilityTable tab_capability = null;
  private UserTable tab_user = null;
  private GroupTable tab_group = null;
  private GroupMembershipTable tab_groupmembership = null;
  private GroupCapabilityTable tab_groupcapability = null;

  public PoemDatabaseBase() {
    try {
      defineTable(tab_tableinfo = new TableInfoTable(this, "tableinfo"));
      defineTable(tab_columninfo = new ColumnInfoTable(this, "columninfo"));
      defineTable(tab_capability = new CapabilityTable(this, "capability"));
      defineTable(tab_user = new UserTable(this, "user"));
      defineTable(tab_group = new GroupTable(this, "group"));
      defineTable(tab_groupmembership = new GroupMembershipTable(this, "groupmembership"));
      defineTable(tab_groupcapability = new GroupCapabilityTable(this, "groupcapability"));
      tab_tableinfo.init();
      tab_columninfo.init();
      tab_capability.init();
      tab_user.init();
      tab_group.init();
      tab_groupmembership.init();
      tab_groupcapability.init();
    }
    catch (PoemException e) {
      throw new UnexpectedExceptionPoemException(e);
    }
  }

  public TableInfoTable getTableInfoTable() {
    return tab_tableinfo;
  }

  public ColumnInfoTable getColumnInfoTable() {
    return tab_columninfo;
  }

  public CapabilityTable getCapabilityTable() {
    return tab_capability;
  }

  public UserTable getUserTable() {
    return tab_user;
  }

  public GroupTable getGroupTable() {
    return tab_group;
  }

  public GroupMembershipTable getGroupMembershipTable() {
    return tab_groupmembership;
  }

  public GroupCapabilityTable getGroupCapabilityTable() {
    return tab_groupcapability;
  }
}
