// Do not edit this file!  It was generated by Melati Poem's DSD preprocessor.

package org.melati.poem;

public class TableInfoDataBase extends Data {
  Integer id;
  String name;
  String displayname;
  String description;
  Integer displayorder;
  Integer defaultcanread;
  Integer defaultcanwrite;
  Integer cancreate;
}
