// Do not edit this file!  It was generated by Melati POEM's DSD preprocessor.

package org.melati.poem;

public class TableInfoBase extends Persistent {

  public TableInfoTable getTableInfoTable() {
    return (TableInfoTable)getTable();
  }

  Integer id;
  String name;
  String displayname;
  String description;
  Integer displayorder;
  Integer defaultcanread;
  Integer defaultcanwrite;
  Integer cancreate;
  Integer cachelimit;
  Boolean seqcached;

  public Integer getId_unsafe() {
    return id;
  }

  public void setId_unsafe(Integer value) {
    id = value;
  }

  public Integer getId()
      throws AccessPoemException {
    readLock();
    return getId_unsafe();
  }

  public void setId(Integer value)
      throws AccessPoemException, ValidationPoemException {
    getTableInfoTable().getIdColumn().getType().assertValidValue(value);
    writeLock();
    setId_unsafe(value);
  }

  public final void setId(int value)
      throws AccessPoemException, ValidationPoemException {
    setId(new Integer(value));
  }

  public final Field getIdField() throws AccessPoemException {
    return getTableInfoTable().getIdColumn().asField(this);
  }

  public String getName_unsafe() {
    return name;
  }

  public void setName_unsafe(String value) {
    name = value;
  }

  public String getName()
      throws AccessPoemException {
    readLock();
    return getName_unsafe();
  }

  public void setName(String value)
      throws AccessPoemException, ValidationPoemException {
    getTableInfoTable().getNameColumn().getType().assertValidValue(value);
    writeLock();
    setName_unsafe(value);
  }

  public final Field getNameField() throws AccessPoemException {
    return getTableInfoTable().getNameColumn().asField(this);
  }

  public String getDisplayname_unsafe() {
    return displayname;
  }

  public void setDisplayname_unsafe(String value) {
    displayname = value;
  }

  public String getDisplayname()
      throws AccessPoemException {
    readLock();
    return getDisplayname_unsafe();
  }

  public void setDisplayname(String value)
      throws AccessPoemException, ValidationPoemException {
    getTableInfoTable().getDisplaynameColumn().getType().assertValidValue(value);
    writeLock();
    setDisplayname_unsafe(value);
  }

  public final Field getDisplaynameField() throws AccessPoemException {
    return getTableInfoTable().getDisplaynameColumn().asField(this);
  }

  public String getDescription_unsafe() {
    return description;
  }

  public void setDescription_unsafe(String value) {
    description = value;
  }

  public String getDescription()
      throws AccessPoemException {
    readLock();
    return getDescription_unsafe();
  }

  public void setDescription(String value)
      throws AccessPoemException, ValidationPoemException {
    getTableInfoTable().getDescriptionColumn().getType().assertValidValue(value);
    writeLock();
    setDescription_unsafe(value);
  }

  public final Field getDescriptionField() throws AccessPoemException {
    return getTableInfoTable().getDescriptionColumn().asField(this);
  }

  public Integer getDisplayorder_unsafe() {
    return displayorder;
  }

  public void setDisplayorder_unsafe(Integer value) {
    displayorder = value;
  }

  public Integer getDisplayorder()
      throws AccessPoemException {
    readLock();
    return getDisplayorder_unsafe();
  }

  public void setDisplayorder(Integer value)
      throws AccessPoemException, ValidationPoemException {
    getTableInfoTable().getDisplayorderColumn().getType().assertValidValue(value);
    writeLock();
    setDisplayorder_unsafe(value);
  }

  public final void setDisplayorder(int value)
      throws AccessPoemException, ValidationPoemException {
    setDisplayorder(new Integer(value));
  }

  public final Field getDisplayorderField() throws AccessPoemException {
    return getTableInfoTable().getDisplayorderColumn().asField(this);
  }

  public Integer getDefaultcanread_unsafe() {
    return defaultcanread;
  }

  public void setDefaultcanread_unsafe(Integer value) {
    defaultcanread = value;
  }

  public Integer getDefaultcanreadTroid()
      throws AccessPoemException {
    readLock();
    return getDefaultcanread_unsafe();
  }

  public void setDefaultcanreadTroid(Integer ident)
      throws AccessPoemException {
    getTableInfoTable().getDefaultcanreadColumn().getType().assertValidIdent(ident);
    writeLock();
    setDefaultcanread_unsafe(ident);
  }

  public Capability getDefaultcanread()
      throws AccessPoemException, NoSuchRowPoemException {
    Integer troid = getDefaultcanreadTroid();
    return troid == null ? null :
        ((PoemDatabase)getDatabase()).getCapabilityTable().getCapabilityObject(troid);
  }

  public void setDefaultcanread(Capability value)
      throws AccessPoemException {
    setDefaultcanreadTroid(value == null ? null : value.troid());
  }

  public final Field getDefaultcanreadField() throws AccessPoemException {
    return getTableInfoTable().getDefaultcanreadColumn().asField(this);
  }

  public Integer getDefaultcanwrite_unsafe() {
    return defaultcanwrite;
  }

  public void setDefaultcanwrite_unsafe(Integer value) {
    defaultcanwrite = value;
  }

  public Integer getDefaultcanwriteTroid()
      throws AccessPoemException {
    readLock();
    return getDefaultcanwrite_unsafe();
  }

  public void setDefaultcanwriteTroid(Integer ident)
      throws AccessPoemException {
    getTableInfoTable().getDefaultcanwriteColumn().getType().assertValidIdent(ident);
    writeLock();
    setDefaultcanwrite_unsafe(ident);
  }

  public Capability getDefaultcanwrite()
      throws AccessPoemException, NoSuchRowPoemException {
    Integer troid = getDefaultcanwriteTroid();
    return troid == null ? null :
        ((PoemDatabase)getDatabase()).getCapabilityTable().getCapabilityObject(troid);
  }

  public void setDefaultcanwrite(Capability value)
      throws AccessPoemException {
    setDefaultcanwriteTroid(value == null ? null : value.troid());
  }

  public final Field getDefaultcanwriteField() throws AccessPoemException {
    return getTableInfoTable().getDefaultcanwriteColumn().asField(this);
  }

  public Integer getCancreate_unsafe() {
    return cancreate;
  }

  public void setCancreate_unsafe(Integer value) {
    cancreate = value;
  }

  public Integer getCancreateTroid()
      throws AccessPoemException {
    readLock();
    return getCancreate_unsafe();
  }

  public void setCancreateTroid(Integer ident)
      throws AccessPoemException {
    getTableInfoTable().getCancreateColumn().getType().assertValidIdent(ident);
    writeLock();
    setCancreate_unsafe(ident);
  }

  public Capability getCancreate()
      throws AccessPoemException, NoSuchRowPoemException {
    Integer troid = getCancreateTroid();
    return troid == null ? null :
        ((PoemDatabase)getDatabase()).getCapabilityTable().getCapabilityObject(troid);
  }

  public void setCancreate(Capability value)
      throws AccessPoemException {
    setCancreateTroid(value == null ? null : value.troid());
  }

  public final Field getCancreateField() throws AccessPoemException {
    return getTableInfoTable().getCancreateColumn().asField(this);
  }

  public Integer getCachelimit_unsafe() {
    return cachelimit;
  }

  public void setCachelimit_unsafe(Integer value) {
    cachelimit = value;
  }

  public Integer getCachelimit()
      throws AccessPoemException {
    readLock();
    return getCachelimit_unsafe();
  }

  public void setCachelimit(Integer value)
      throws AccessPoemException, ValidationPoemException {
    getTableInfoTable().getCachelimitColumn().getType().assertValidValue(value);
    writeLock();
    setCachelimit_unsafe(value);
  }

  public final void setCachelimit(int value)
      throws AccessPoemException, ValidationPoemException {
    setCachelimit(new Integer(value));
  }

  public final Field getCachelimitField() throws AccessPoemException {
    return getTableInfoTable().getCachelimitColumn().asField(this);
  }

  public Boolean getSeqcached_unsafe() {
    return seqcached;
  }

  public void setSeqcached_unsafe(Boolean value) {
    seqcached = value;
  }

  public Boolean getSeqcached()
      throws AccessPoemException {
    readLock();
    return getSeqcached_unsafe();
  }

  public void setSeqcached(Boolean value)
      throws AccessPoemException, ValidationPoemException {
    getTableInfoTable().getSeqcachedColumn().getType().assertValidValue(value);
    writeLock();
    setSeqcached_unsafe(value);
  }

  public final void setSeqcached(boolean value)
      throws AccessPoemException, ValidationPoemException {
    setSeqcached(value ? Boolean.TRUE : Boolean.FALSE);
  }

  public final Field getSeqcachedField() throws AccessPoemException {
    return getTableInfoTable().getSeqcachedColumn().asField(this);
  }
}
