// Do not edit this file!  It was generated by Melati Poem's DSD preprocessor.

package org.melati.poem;

public class TableInfoTable extends Table {

  private Column col_id = null;
  private Column col_name = null;

  public TableInfoTable(Database database, String name) throws PoemException {
    super(database, name, DefinitionSource.dsd);
  }

  protected void init() throws PoemException {
    defineColumn(col_id =
        new Column(this, "id", TroidPoemType.it, DefinitionSource.dsd) { 
          public Object getIdent(Fields fields) {
            return (Integer)((TableInfoFields)fields).id;
          }

          public void setIdent(Fields fields, Object ident) {
            ((TableInfoFields)fields).id = (Integer)ident;
          }

          public Object getValue(Persistent g)
              throws AccessPoemException, PoemException {
            return ((TableInfo)g).getId();
          }

          public void setValue(Persistent g, Object value)
              throws AccessPoemException, ValidationPoemException {
            ((TableInfo)g).setId((Integer)value);
          }

          public Object getIdent(Persistent g)
              throws AccessPoemException {
            return ((TableInfo)g).getId();
          }

          public void setIdent(Persistent g, Object ident)
              throws AccessPoemException {
            ((TableInfo)g).setId((Integer)ident);
          }
        });

    defineColumn(col_name =
        new Column(this, "name", new StringPoemType(false, 50), DefinitionSource.dsd) { 
          public Object getIdent(Fields fields) {
            return (String)((TableInfoFields)fields).name;
          }

          public void setIdent(Fields fields, Object ident) {
            ((TableInfoFields)fields).name = (String)ident;
          }

          public Object getValue(Persistent g)
              throws AccessPoemException, PoemException {
            return ((TableInfo)g).getName();
          }

          public void setValue(Persistent g, Object value)
              throws AccessPoemException, ValidationPoemException {
            ((TableInfo)g).setName((String)value);
          }

          public Object getIdent(Persistent g)
              throws AccessPoemException {
            return ((TableInfo)g).getName();
          }

          public void setIdent(Persistent g, Object ident)
              throws AccessPoemException {
            ((TableInfo)g).setName((String)ident);
          }
        });
  }

  public Column getIdColumn() {
    return col_id;
  }

  public Column getNameColumn() {
    return col_name;
  }

  public TableInfo getTableInfoObject(Integer troid) {
    return (TableInfo)getObject(troid);
  }

  protected Persistent newPersistent() {
    return new TableInfo();
  }
}
