// Do not edit this file!  It was generated by Melati Poem's DSD preprocessor.

package org.melati.poem;

class UserBase extends Persistent {

  public final UserData dataSnapshot()
      throws AccessPoemException {
    return (UserData)_dataSnapshot();
  }

  protected final UserData dataForReading()
      throws AccessPoemException {
    return (UserData)_dataForReading();
  }

  protected final UserData dataForWriting()
      throws AccessPoemException {
    return (UserData)_dataForWriting();
  }

  public UserTable getUserTable() {
    return (UserTable)getTable();
  }

  public Integer getId()
      throws AccessPoemException {
    return dataForReading().id;
  }

  public void setId(Integer value)
      throws AccessPoemException, ValidationPoemException {
    getUserTable().getIdColumn().getType().assertValidValue(value);
    dataForWriting().id = value;
  }

  public final void setId(int value)
      throws AccessPoemException, ValidationPoemException {
    setId(new Integer(value));
  }

  public final Field getIdField() throws AccessPoemException {
    return getUserTable().getIdColumn().asField(this);
  }

  public String getName()
      throws AccessPoemException {
    return dataForReading().name;
  }

  public void setName(String value)
      throws AccessPoemException, ValidationPoemException {
    getUserTable().getNameColumn().getType().assertValidValue(value);
    dataForWriting().name = value;
  }

  public final Field getNameField() throws AccessPoemException {
    return getUserTable().getNameColumn().asField(this);
  }
}
