// Do not edit this file!  It was generated by Melati Poem's DSD preprocessor.

package org.melati.poem;

public class UserDataBase extends Data {
  Integer id;
  String login;
  String password;
  String name;
}
